name: GitHub Pages Build

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Typo check
        uses: crate-ci/typos@v1.0.4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Check broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://${{ github.event.repository.name }}
          pages_path: ./public
          cmd_params: "\
            --timeout=20 \
            --max-connections=10 \
            -e linkedin.com \
            -e twitter.com \
            -e facebook.com \
            -e gstatic.com \
            -e researchgate.net \
            -e arxiv.org \
            -e valuenex.com \
            -e challenge2018.isic-archive.com \
            -e paper-survey \
            -e publication/#\\d \
            -e index.webmanifest \
            "
            
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: gh-pages # deploying branch

